name: fx1-nft-marketplace
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Ensure Vite is installed
        run: npm install vite --save-dev

      - name: Build project
        run: npm run build

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
